/*
 Navicat Premium Data Transfer

 Source Server         : oracle
 Source Server Type    : Oracle
 Source Server Version : 190000 (Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production)
 Source Host           : localhost:1521
 Source Schema         : WENSON

 Target Server Type    : Oracle
 Target Server Version : 190000 (Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production)
 File Encoding         : 65001

 Date: 06/12/2023 21:28:56
*/


-- ----------------------------
-- Table structure for CHONGWUXINXI
-- ----------------------------
DROP TABLE "WENSON"."CHONGWUXINXI";
CREATE TABLE "WENSON"."CHONGWUXINXI" (
  "ID" NUMBER(20,0) VISIBLE NOT NULL,
  "ADDTIME" DATE VISIBLE NOT NULL,
  "CHONGWUBIANHAO" NVARCHAR2(200) VISIBLE,
  "CHONGWUMINGCHENG" NVARCHAR2(200) VISIBLE NOT NULL,
  "PINZHONG" NVARCHAR2(200) VISIBLE NOT NULL,
  "TUPIAN" NVARCHAR2(200) VISIBLE,
  "NIANLING" NUMBER(11,0) VISIBLE,
  "CHONGWUXIANGQING" NCLOB VISIBLE,
  "CLICKTIME" DATE VISIBLE,
  "CLICKNUM" NUMBER(11,0) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "WENSON"."CHONGWUXINXI"."ID" IS '主键';
COMMENT ON COLUMN "WENSON"."CHONGWUXINXI"."ADDTIME" IS '创建时间';
COMMENT ON COLUMN "WENSON"."CHONGWUXINXI"."CHONGWUBIANHAO" IS '宠物编号';
COMMENT ON COLUMN "WENSON"."CHONGWUXINXI"."CHONGWUMINGCHENG" IS '宠物名称';
COMMENT ON COLUMN "WENSON"."CHONGWUXINXI"."PINZHONG" IS '品种';
COMMENT ON COLUMN "WENSON"."CHONGWUXINXI"."TUPIAN" IS '图片';
COMMENT ON COLUMN "WENSON"."CHONGWUXINXI"."NIANLING" IS '年龄';
COMMENT ON COLUMN "WENSON"."CHONGWUXINXI"."CHONGWUXIANGQING" IS '宠物详情';
COMMENT ON COLUMN "WENSON"."CHONGWUXINXI"."CLICKTIME" IS '最近点击时间';
COMMENT ON COLUMN "WENSON"."CHONGWUXINXI"."CLICKNUM" IS '点击次数';
COMMENT ON TABLE "WENSON"."CHONGWUXINXI" IS '宠物信息';

-- ----------------------------
-- Records of CHONGWUXINXI
-- ----------------------------
INSERT INTO "WENSON"."CHONGWUXINXI" VALUES ('1701762407786', TO_DATE('2023-12-05 15:46:47', 'SYYYY-MM-DD HH24:MI:SS'), '1701762376908', '贵妇犬', '犬类', 'http://localhost:8080/petHospital/upload/1701762389654.png', '5', '<p>优雅</p>', TO_DATE('2023-12-06 20:55:20', 'SYYYY-MM-DD HH24:MI:SS'), '7');
INSERT INTO "WENSON"."CHONGWUXINXI" VALUES ('1701762481947', TO_DATE('2023-12-05 15:48:01', 'SYYYY-MM-DD HH24:MI:SS'), '1701762460345', '雷鸣仙', '鱼类', 'http://localhost:8080/petHospital/upload/1701762464308.png', '1', '<p>霸气</p>', TO_DATE('2023-12-06 20:55:08', 'SYYYY-MM-DD HH24:MI:SS'), '6');
INSERT INTO "WENSON"."CHONGWUXINXI" VALUES ('1701867433065', TO_DATE('2023-12-06 20:57:12', 'SYYYY-MM-DD HH24:MI:SS'), '1701867416929', '玳龟', '龟', 'http://localhost:8080/petHospital/upload/1701867423380.png', '25', NULL, TO_DATE('2023-12-06 20:58:02', 'SYYYY-MM-DD HH24:MI:SS'), '3');

-- ----------------------------
-- Table structure for CONFIG
-- ----------------------------
DROP TABLE "WENSON"."CONFIG";
CREATE TABLE "WENSON"."CONFIG" (
  "ID" NUMBER(20,0) VISIBLE NOT NULL,
  "NAME" NVARCHAR2(100) VISIBLE NOT NULL,
  "VALUE" NVARCHAR2(100) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "WENSON"."CONFIG"."ID" IS '主键';
COMMENT ON COLUMN "WENSON"."CONFIG"."NAME" IS '配置参数名称';
COMMENT ON COLUMN "WENSON"."CONFIG"."VALUE" IS '配置参数值';
COMMENT ON TABLE "WENSON"."CONFIG" IS '配置文件';

-- ----------------------------
-- Records of CONFIG
-- ----------------------------
INSERT INTO "WENSON"."CONFIG" VALUES ('1', 'picture1', 'http://localhost:8080/petHospital/upload/1701626986582.jpg');
INSERT INTO "WENSON"."CONFIG" VALUES ('2', 'picture2', 'http://localhost:8080/petHospital/upload/1701626995592.jpg');
INSERT INTO "WENSON"."CONFIG" VALUES ('3', 'picture3', 'http://localhost:8080/petHospital/upload/1701627003284.jpg');
INSERT INTO "WENSON"."CONFIG" VALUES ('6', 'homepage', 'http://localhost:8080/petHospital/upload/1701627025473.jpg');

-- ----------------------------
-- Table structure for FORUM
-- ----------------------------
DROP TABLE "WENSON"."FORUM";
CREATE TABLE "WENSON"."FORUM" (
  "ID" NUMBER(20,0) VISIBLE NOT NULL,
  "ADDTIME" DATE VISIBLE NOT NULL,
  "TITLE" NVARCHAR2(200) VISIBLE,
  "CONTENT" NCLOB VISIBLE NOT NULL,
  "PARENTID" NUMBER(20,0) VISIBLE,
  "USERID" NUMBER(20,0) VISIBLE NOT NULL,
  "USERNAME" NVARCHAR2(200) VISIBLE,
  "ISDONE" NVARCHAR2(200) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "WENSON"."FORUM"."ID" IS '主键';
COMMENT ON COLUMN "WENSON"."FORUM"."ADDTIME" IS '创建时间';
COMMENT ON COLUMN "WENSON"."FORUM"."TITLE" IS '帖子标题';
COMMENT ON COLUMN "WENSON"."FORUM"."CONTENT" IS '帖子内容';
COMMENT ON COLUMN "WENSON"."FORUM"."PARENTID" IS '父节点id';
COMMENT ON COLUMN "WENSON"."FORUM"."USERID" IS '用户id';
COMMENT ON COLUMN "WENSON"."FORUM"."USERNAME" IS '用户名';
COMMENT ON COLUMN "WENSON"."FORUM"."ISDONE" IS '状态';
COMMENT ON TABLE "WENSON"."FORUM" IS '宠物论坛';

-- ----------------------------
-- Records of FORUM
-- ----------------------------
INSERT INTO "WENSON"."FORUM" VALUES ('1701762194679', TO_DATE('2023-12-05 15:43:14', 'SYYYY-MM-DD HH24:MI:SS'), 'test', '<p>666</p>
<div id="gtx-trans" style="position: absolute; left: -235px; top: -12px;">
<div class="gtx-trans-icon">&nbsp;</div>
</div>', '0', '1618488891531', '01', '开放');

-- ----------------------------
-- Table structure for GUAHAOYUYUE
-- ----------------------------
DROP TABLE "WENSON"."GUAHAOYUYUE";
CREATE TABLE "WENSON"."GUAHAOYUYUE" (
  "ID" NUMBER(20,0) VISIBLE NOT NULL,
  "ADDTIME" DATE VISIBLE NOT NULL,
  "SHOULING" NUMBER(11,0) VISIBLE,
  "CHONGWUXINXI" NCLOB VISIBLE,
  "YISHENGXINGMING" NVARCHAR2(200) VISIBLE,
  "YUYUESHIJIAN" DATE VISIBLE,
  "YONGHUMING" NVARCHAR2(200) VISIBLE NOT NULL,
  "XINGMING" NVARCHAR2(200) VISIBLE,
  "SFSH" NVARCHAR2(200) VISIBLE,
  "SHHF" NCLOB VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "WENSON"."GUAHAOYUYUE"."ID" IS '主键';
COMMENT ON COLUMN "WENSON"."GUAHAOYUYUE"."ADDTIME" IS '创建时间';
COMMENT ON COLUMN "WENSON"."GUAHAOYUYUE"."SHOULING" IS '兽龄';
COMMENT ON COLUMN "WENSON"."GUAHAOYUYUE"."CHONGWUXINXI" IS '宠物信息';
COMMENT ON COLUMN "WENSON"."GUAHAOYUYUE"."YISHENGXINGMING" IS '医生姓名';
COMMENT ON COLUMN "WENSON"."GUAHAOYUYUE"."YUYUESHIJIAN" IS '预约时间';
COMMENT ON COLUMN "WENSON"."GUAHAOYUYUE"."YONGHUMING" IS '用户名';
COMMENT ON COLUMN "WENSON"."GUAHAOYUYUE"."XINGMING" IS '姓名';
COMMENT ON COLUMN "WENSON"."GUAHAOYUYUE"."SFSH" IS '是否审核';
COMMENT ON COLUMN "WENSON"."GUAHAOYUYUE"."SHHF" IS '审核回复';
COMMENT ON TABLE "WENSON"."GUAHAOYUYUE" IS '挂号预约';

-- ----------------------------
-- Records of GUAHAOYUYUE
-- ----------------------------
INSERT INTO "WENSON"."GUAHAOYUYUE" VALUES ('1701762183355', TO_DATE('2023-12-05 15:43:02', 'SYYYY-MM-DD HH24:MI:SS'), '18', NULL, '医生姓名1', TO_DATE('2023-12-12 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '01', '01', NULL, NULL);
INSERT INTO "WENSON"."GUAHAOYUYUE" VALUES ('1701761541976', TO_DATE('2023-12-05 15:32:34', 'SYYYY-MM-DD HH24:MI:SS'), '41', NULL, '医生姓名1', TO_DATE('2023-12-05 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '01', '01', NULL, NULL);

-- ----------------------------
-- Table structure for JIYANG
-- ----------------------------
DROP TABLE "WENSON"."JIYANG";
CREATE TABLE "WENSON"."JIYANG" (
  "ID" NUMBER(20,0) VISIBLE NOT NULL,
  "ADDTIME" DATE VISIBLE NOT NULL,
  "YONGHUMING" NVARCHAR2(200) VISIBLE,
  "XINGMING" NVARCHAR2(200) VISIBLE,
  "CHONGWUMINGCHENG" NVARCHAR2(200) VISIBLE,
  "SHOULING" NVARCHAR2(200) VISIBLE,
  "CHONGWUXIANGQING" NCLOB VISIBLE,
  "RIQI" DATE VISIBLE,
  "SFSH" NVARCHAR2(200) VISIBLE,
  "SHHF" NCLOB VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "WENSON"."JIYANG"."ID" IS '主键';
COMMENT ON COLUMN "WENSON"."JIYANG"."ADDTIME" IS '创建时间';
COMMENT ON COLUMN "WENSON"."JIYANG"."YONGHUMING" IS '用户名';
COMMENT ON COLUMN "WENSON"."JIYANG"."XINGMING" IS '姓名';
COMMENT ON COLUMN "WENSON"."JIYANG"."CHONGWUMINGCHENG" IS '宠物名称';
COMMENT ON COLUMN "WENSON"."JIYANG"."SHOULING" IS '兽龄';
COMMENT ON COLUMN "WENSON"."JIYANG"."CHONGWUXIANGQING" IS '宠物详情';
COMMENT ON COLUMN "WENSON"."JIYANG"."RIQI" IS '日期';
COMMENT ON COLUMN "WENSON"."JIYANG"."SFSH" IS '是否审核';
COMMENT ON COLUMN "WENSON"."JIYANG"."SHHF" IS '审核回复';
COMMENT ON TABLE "WENSON"."JIYANG" IS '寄养';

-- ----------------------------
-- Records of JIYANG
-- ----------------------------
INSERT INTO "WENSON"."JIYANG" VALUES ('1701764006733', TO_DATE('2023-12-05 16:13:25', 'SYYYY-MM-DD HH24:MI:SS'), '01', '01', '玳龟', '64', NULL, TO_DATE('2023-12-07 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '是', NULL);

-- ----------------------------
-- Table structure for JIYANGJIEGUO
-- ----------------------------
DROP TABLE "WENSON"."JIYANGJIEGUO";
CREATE TABLE "WENSON"."JIYANGJIEGUO" (
  "ID" NUMBER(20,0) VISIBLE NOT NULL,
  "ADDTIME" DATE VISIBLE NOT NULL,
  "YONGHUMING" NVARCHAR2(200) VISIBLE,
  "XINGMING" NVARCHAR2(200) VISIBLE,
  "CHONGWUMINGCHENG" NVARCHAR2(200) VISIBLE,
  "LINGYANGRIQI" DATE VISIBLE,
  "JIYANGJIEGUO" NVARCHAR2(200) VISIBLE,
  "LINGYANGRENXINGMING" NVARCHAR2(200) VISIBLE,
  "LIANXIFANGSHI" NVARCHAR2(200) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "WENSON"."JIYANGJIEGUO"."ID" IS '主键';
COMMENT ON COLUMN "WENSON"."JIYANGJIEGUO"."ADDTIME" IS '创建时间';
COMMENT ON COLUMN "WENSON"."JIYANGJIEGUO"."YONGHUMING" IS '用户名';
COMMENT ON COLUMN "WENSON"."JIYANGJIEGUO"."XINGMING" IS '姓名';
COMMENT ON COLUMN "WENSON"."JIYANGJIEGUO"."CHONGWUMINGCHENG" IS '宠物名称';
COMMENT ON COLUMN "WENSON"."JIYANGJIEGUO"."LINGYANGRIQI" IS '领养日期';
COMMENT ON COLUMN "WENSON"."JIYANGJIEGUO"."JIYANGJIEGUO" IS '寄养结果';
COMMENT ON COLUMN "WENSON"."JIYANGJIEGUO"."LINGYANGRENXINGMING" IS '领养人姓名';
COMMENT ON COLUMN "WENSON"."JIYANGJIEGUO"."LIANXIFANGSHI" IS '联系方式';
COMMENT ON TABLE "WENSON"."JIYANGJIEGUO" IS '寄养结果';

-- ----------------------------
-- Records of JIYANGJIEGUO
-- ----------------------------
INSERT INTO "WENSON"."JIYANGJIEGUO" VALUES ('1701867735395', TO_DATE('2023-12-06 21:02:14', 'SYYYY-MM-DD HH24:MI:SS'), '01', '01', '玳龟', TO_DATE('2023-12-06 21:02:06', 'SYYYY-MM-DD HH24:MI:SS'), '成功', '02', NULL);

-- ----------------------------
-- Table structure for LINGYANG
-- ----------------------------
DROP TABLE "WENSON"."LINGYANG";
CREATE TABLE "WENSON"."LINGYANG" (
  "ID" NUMBER(20,0) VISIBLE NOT NULL,
  "ADDTIME" DATE VISIBLE NOT NULL,
  "YONGHUMING" NVARCHAR2(200) VISIBLE,
  "XINGMING" NVARCHAR2(200) VISIBLE,
  "CHONGWUBIANHAO" NVARCHAR2(200) VISIBLE,
  "CHONGWUMINGCHENG" NVARCHAR2(200) VISIBLE,
  "RIQI" DATE VISIBLE,
  "SFSH" NVARCHAR2(200) VISIBLE,
  "SHHF" NCLOB VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "WENSON"."LINGYANG"."ID" IS '主键';
COMMENT ON COLUMN "WENSON"."LINGYANG"."ADDTIME" IS '创建时间';
COMMENT ON COLUMN "WENSON"."LINGYANG"."YONGHUMING" IS '用户名';
COMMENT ON COLUMN "WENSON"."LINGYANG"."XINGMING" IS '姓名';
COMMENT ON COLUMN "WENSON"."LINGYANG"."CHONGWUBIANHAO" IS '宠物编号';
COMMENT ON COLUMN "WENSON"."LINGYANG"."CHONGWUMINGCHENG" IS '宠物名称';
COMMENT ON COLUMN "WENSON"."LINGYANG"."RIQI" IS '日期';
COMMENT ON COLUMN "WENSON"."LINGYANG"."SFSH" IS '是否审核';
COMMENT ON COLUMN "WENSON"."LINGYANG"."SHHF" IS '审核回复';
COMMENT ON TABLE "WENSON"."LINGYANG" IS '领养';

-- ----------------------------
-- Records of LINGYANG
-- ----------------------------
INSERT INTO "WENSON"."LINGYANG" VALUES ('1701763931885', TO_DATE('2023-12-05 16:12:10', 'SYYYY-MM-DD HH24:MI:SS'), '01', '01', '1701762376908', '贵妇犬', TO_DATE('2023-12-05 16:12:08', 'SYYYY-MM-DD HH24:MI:SS'), '是', NULL);
INSERT INTO "WENSON"."LINGYANG" VALUES ('1701867480843', TO_DATE('2023-12-06 20:58:00', 'SYYYY-MM-DD HH24:MI:SS'), '02', '02', '1701867416929', '玳龟', TO_DATE('2023-12-06 20:57:58', 'SYYYY-MM-DD HH24:MI:SS'), NULL, NULL);

-- ----------------------------
-- Table structure for NEWS
-- ----------------------------
DROP TABLE "WENSON"."NEWS";
CREATE TABLE "WENSON"."NEWS" (
  "ID" NUMBER(20,0) VISIBLE NOT NULL,
  "ADDTIME" DATE VISIBLE NOT NULL,
  "TITLE" NVARCHAR2(200) VISIBLE NOT NULL,
  "INTRODUCTION" NCLOB VISIBLE,
  "PICTURE" NVARCHAR2(200) VISIBLE NOT NULL,
  "CONTENT" NCLOB VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "WENSON"."NEWS"."ID" IS '主键';
COMMENT ON COLUMN "WENSON"."NEWS"."ADDTIME" IS '创建时间';
COMMENT ON COLUMN "WENSON"."NEWS"."TITLE" IS '标题';
COMMENT ON COLUMN "WENSON"."NEWS"."INTRODUCTION" IS '简介';
COMMENT ON COLUMN "WENSON"."NEWS"."PICTURE" IS '图片';
COMMENT ON COLUMN "WENSON"."NEWS"."CONTENT" IS '内容';
COMMENT ON TABLE "WENSON"."NEWS" IS '网站公告';

-- ----------------------------
-- Records of NEWS
-- ----------------------------
INSERT INTO "WENSON"."NEWS" VALUES ('101', TO_DATE('2023-12-05 20:04:52', 'SYYYY-MM-DD HH24:MI:SS'), '标题1', '简介1', 'http://localhost:8080/petHospital/upload/1701763734456.png', '<p>内容1</p>');
INSERT INTO "WENSON"."NEWS" VALUES ('102', TO_DATE('2023-12-05 20:04:52', 'SYYYY-MM-DD HH24:MI:SS'), '标题2', '简介2', 'http://localhost:8080/petHospital/upload/1701763744981.png', '<p>内容2</p>');
INSERT INTO "WENSON"."NEWS" VALUES ('103', TO_DATE('2023-12-05 20:04:52', 'SYYYY-MM-DD HH24:MI:SS'), '标题3', '简介3', 'http://localhost:8080/petHospital/upload/1701763754922.png', '<p>内容3</p>');
INSERT INTO "WENSON"."NEWS" VALUES ('104', TO_DATE('2023-12-05 20:04:52', 'SYYYY-MM-DD HH24:MI:SS'), '标题4', '简介4', 'http://localhost:8080/petHospital/upload/1701763770501.png', '<p>内容4</p>');

-- ----------------------------
-- Table structure for STOREUP
-- ----------------------------
DROP TABLE "WENSON"."STOREUP";
CREATE TABLE "WENSON"."STOREUP" (
  "ID" NUMBER(20,0) VISIBLE NOT NULL,
  "ADDTIME" DATE VISIBLE NOT NULL,
  "USERID" NUMBER(20,0) VISIBLE NOT NULL,
  "REFID" NUMBER(20,0) VISIBLE,
  "TABLENAME" NVARCHAR2(200) VISIBLE,
  "NAME" NVARCHAR2(200) VISIBLE NOT NULL,
  "PICTURE" NVARCHAR2(200) VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "WENSON"."STOREUP"."ID" IS '主键';
COMMENT ON COLUMN "WENSON"."STOREUP"."ADDTIME" IS '创建时间';
COMMENT ON COLUMN "WENSON"."STOREUP"."USERID" IS '用户id';
COMMENT ON COLUMN "WENSON"."STOREUP"."REFID" IS '收藏id';
COMMENT ON COLUMN "WENSON"."STOREUP"."TABLENAME" IS '表名';
COMMENT ON COLUMN "WENSON"."STOREUP"."NAME" IS '收藏名称';
COMMENT ON COLUMN "WENSON"."STOREUP"."PICTURE" IS '收藏图片';
COMMENT ON TABLE "WENSON"."STOREUP" IS '收藏表';

-- ----------------------------
-- Records of STOREUP
-- ----------------------------
INSERT INTO "WENSON"."STOREUP" VALUES ('1701867307962', TO_DATE('2023-12-06 20:55:07', 'SYYYY-MM-DD HH24:MI:SS'), '1701764322363', '1701762481947', 'chongwuxinxi', '雷鸣仙', 'http://localhost:8080/petHospital/upload/1701762464308.png');
INSERT INTO "WENSON"."STOREUP" VALUES ('1701763925669', TO_DATE('2023-12-05 16:12:05', 'SYYYY-MM-DD HH24:MI:SS'), '1618488891531', '1701762407786', 'chongwuxinxi', '贵妇犬', 'http://localhost:8080/petHospital/upload/1701762389654.png');

-- ----------------------------
-- Table structure for TOKEN
-- ----------------------------
DROP TABLE "WENSON"."TOKEN";
CREATE TABLE "WENSON"."TOKEN" (
  "ID" NUMBER(20,0) VISIBLE NOT NULL,
  "USERID" NUMBER(20,0) VISIBLE NOT NULL,
  "USERNAME" NVARCHAR2(100) VISIBLE NOT NULL,
  "TABLENAME" NVARCHAR2(100) VISIBLE,
  "ROLE" NVARCHAR2(100) VISIBLE,
  "TOKEN" NVARCHAR2(200) VISIBLE NOT NULL,
  "ADDTIME" DATE VISIBLE NOT NULL,
  "EXPIRATEDTIME" DATE VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "WENSON"."TOKEN"."ID" IS '主键';
COMMENT ON COLUMN "WENSON"."TOKEN"."USERID" IS '用户id';
COMMENT ON COLUMN "WENSON"."TOKEN"."USERNAME" IS '用户名';
COMMENT ON COLUMN "WENSON"."TOKEN"."TABLENAME" IS '表名';
COMMENT ON COLUMN "WENSON"."TOKEN"."ROLE" IS '角色';
COMMENT ON COLUMN "WENSON"."TOKEN"."TOKEN" IS '密码';
COMMENT ON COLUMN "WENSON"."TOKEN"."ADDTIME" IS '新增时间';
COMMENT ON COLUMN "WENSON"."TOKEN"."EXPIRATEDTIME" IS '过期时间';
COMMENT ON TABLE "WENSON"."TOKEN" IS 'token表';

-- ----------------------------
-- Records of TOKEN
-- ----------------------------
INSERT INTO "WENSON"."TOKEN" VALUES ('3', '1701764322363', '02', 'yonghu', '用户', 'fk7xjcudmbf532t7qu9ksrcjhlsveyq5', TO_DATE('2023-12-06 01:48:22', 'SYYYY-MM-DD HH24:MI:SS'), TO_DATE('2023-12-06 21:57:56', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "WENSON"."TOKEN" VALUES ('1', '1618488891531', '01', 'yonghu', '用户', 'eo3mh85m4opho3x4r02t64hr18ukh4sl', TO_DATE('2023-12-06 01:48:22', 'SYYYY-MM-DD HH24:MI:SS'), TO_DATE('2023-12-06 21:59:27', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "WENSON"."TOKEN" VALUES ('2', '1', 'admin', 'users', '管理员', '5odfys8ztvnvghdimzlixlakv3em21jh', TO_DATE('2023-12-06 01:48:22', 'SYYYY-MM-DD HH24:MI:SS'), TO_DATE('2023-12-06 22:00:14', 'SYYYY-MM-DD HH24:MI:SS'));

-- ----------------------------
-- Table structure for USERS
-- ----------------------------
DROP TABLE "WENSON"."USERS";
CREATE TABLE "WENSON"."USERS" (
  "ID" NUMBER(20,0) VISIBLE NOT NULL,
  "USERNAME" NVARCHAR2(100) VISIBLE NOT NULL,
  "PASSWORD" NVARCHAR2(100) VISIBLE NOT NULL,
  "ROLE" NVARCHAR2(100) VISIBLE,
  "ADDTIME" DATE VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "WENSON"."USERS"."ID" IS '主键';
COMMENT ON COLUMN "WENSON"."USERS"."USERNAME" IS '用户名';
COMMENT ON COLUMN "WENSON"."USERS"."PASSWORD" IS '密码';
COMMENT ON COLUMN "WENSON"."USERS"."ROLE" IS '角色';
COMMENT ON COLUMN "WENSON"."USERS"."ADDTIME" IS '新增时间';
COMMENT ON TABLE "WENSON"."USERS" IS '用户表';

-- ----------------------------
-- Records of USERS
-- ----------------------------
INSERT INTO "WENSON"."USERS" VALUES ('1', 'admin', 'admin', '管理员', TO_DATE('2023-12-06 01:48:22', 'SYYYY-MM-DD HH24:MI:SS'));

-- ----------------------------
-- Table structure for YISHENGXINXI
-- ----------------------------
DROP TABLE "WENSON"."YISHENGXINXI";
CREATE TABLE "WENSON"."YISHENGXINXI" (
  "ID" NUMBER(20,0) VISIBLE NOT NULL,
  "ADDTIME" DATE VISIBLE NOT NULL,
  "YISHENGXINGMING" NVARCHAR2(200) VISIBLE,
  "ZHICHENG" NVARCHAR2(200) VISIBLE,
  "XINGBIE" NVARCHAR2(200) VISIBLE,
  "YISHENGJIANJIE" NCLOB VISIBLE,
  "LIANXIDIANHUA" NVARCHAR2(200) VISIBLE,
  "YOUXIANG" NVARCHAR2(200) VISIBLE,
  "ZHAOPIAN" NVARCHAR2(200) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "WENSON"."YISHENGXINXI"."ID" IS '主键';
COMMENT ON COLUMN "WENSON"."YISHENGXINXI"."ADDTIME" IS '创建时间';
COMMENT ON COLUMN "WENSON"."YISHENGXINXI"."YISHENGXINGMING" IS '医生姓名';
COMMENT ON COLUMN "WENSON"."YISHENGXINXI"."ZHICHENG" IS '职称';
COMMENT ON COLUMN "WENSON"."YISHENGXINXI"."XINGBIE" IS '性别';
COMMENT ON COLUMN "WENSON"."YISHENGXINXI"."YISHENGJIANJIE" IS '医生简介';
COMMENT ON COLUMN "WENSON"."YISHENGXINXI"."LIANXIDIANHUA" IS '联系电话';
COMMENT ON COLUMN "WENSON"."YISHENGXINXI"."YOUXIANG" IS '邮箱';
COMMENT ON COLUMN "WENSON"."YISHENGXINXI"."ZHAOPIAN" IS '照片';
COMMENT ON TABLE "WENSON"."YISHENGXINXI" IS '医生信息';

-- ----------------------------
-- Records of YISHENGXINXI
-- ----------------------------
INSERT INTO "WENSON"."YISHENGXINXI" VALUES ('41', TO_DATE('2023-12-06 01:48:22', 'SYYYY-MM-DD HH24:MI:SS'), '医生姓名1', '职称1', '女', '<p>医生简介1</p>', '13823888881', '773890001@qq.com', 'http://localhost:8080/petHospital/upload/1701626588368.png');
INSERT INTO "WENSON"."YISHENGXINXI" VALUES ('43', TO_DATE('2023-12-06 01:48:22', 'SYYYY-MM-DD HH24:MI:SS'), '医生姓名3', '职称3', '女', '<p>医生简介3</p>', '13823888883', '773890003@qq.com', 'http://localhost:8080/petHospital/upload/1701626653029.png');
INSERT INTO "WENSON"."YISHENGXINXI" VALUES ('45', TO_DATE('2023-12-06 01:48:22', 'SYYYY-MM-DD HH24:MI:SS'), '医生姓名5', '职称5', '女', '<p>医生简介5</p>', '13823888885', '773890005@qq.com', 'http://localhost:8080/petHospital/upload/1701626665490.png');
INSERT INTO "WENSON"."YISHENGXINXI" VALUES ('46', TO_DATE('2023-12-06 01:48:22', 'SYYYY-MM-DD HH24:MI:SS'), '医生姓名6', '职称6', '女', '<p>医生简介6</p>', '13823888886', '773890006@qq.com', 'http://localhost:8080/petHospital/upload/1701626677314.png');

-- ----------------------------
-- Table structure for YONGHU
-- ----------------------------
DROP TABLE "WENSON"."YONGHU";
CREATE TABLE "WENSON"."YONGHU" (
  "ID" NUMBER(20,0) VISIBLE NOT NULL,
  "ADDTIME" DATE VISIBLE NOT NULL,
  "YONGHUMING" NVARCHAR2(200) VISIBLE NOT NULL,
  "MIMA" NVARCHAR2(200) VISIBLE NOT NULL,
  "XINGMING" NVARCHAR2(200) VISIBLE NOT NULL,
  "XINGBIE" NVARCHAR2(200) VISIBLE,
  "NIANLING" NUMBER(11,0) VISIBLE,
  "SHOUJI" NVARCHAR2(200) VISIBLE,
  "YOUXIANG" NVARCHAR2(200) VISIBLE,
  "TOUXIANG" NVARCHAR2(200) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "WENSON"."YONGHU"."ID" IS '主键';
COMMENT ON COLUMN "WENSON"."YONGHU"."ADDTIME" IS '创建时间';
COMMENT ON COLUMN "WENSON"."YONGHU"."YONGHUMING" IS '用户名';
COMMENT ON COLUMN "WENSON"."YONGHU"."MIMA" IS '密码';
COMMENT ON COLUMN "WENSON"."YONGHU"."XINGMING" IS '姓名';
COMMENT ON COLUMN "WENSON"."YONGHU"."XINGBIE" IS '性别';
COMMENT ON COLUMN "WENSON"."YONGHU"."NIANLING" IS '年龄';
COMMENT ON COLUMN "WENSON"."YONGHU"."SHOUJI" IS '手机';
COMMENT ON COLUMN "WENSON"."YONGHU"."YOUXIANG" IS '邮箱';
COMMENT ON COLUMN "WENSON"."YONGHU"."TOUXIANG" IS '头像';
COMMENT ON TABLE "WENSON"."YONGHU" IS '用户';

-- ----------------------------
-- Records of YONGHU
-- ----------------------------
INSERT INTO "WENSON"."YONGHU" VALUES ('11', TO_DATE('2023-12-06 01:48:22', 'SYYYY-MM-DD HH24:MI:SS'), '用户1', '123456', '姓名1', '女', '1', '13823888881', '773890001@qq.com', 'http://localhost:8080/petHospital/upload/1701626757524.png');
INSERT INTO "WENSON"."YONGHU" VALUES ('12', TO_DATE('2023-12-06 01:48:22', 'SYYYY-MM-DD HH24:MI:SS'), '用户2', '123456', '姓名2', '男', '2', '13823888882', '773890002@qq.com', 'http://localhost:8080/petHospital/upload/1701626767134.png');
INSERT INTO "WENSON"."YONGHU" VALUES ('13', TO_DATE('2023-12-06 01:48:22', 'SYYYY-MM-DD HH24:MI:SS'), '用户3', '123456', '姓名3', '男', '3', '13823888883', '773890003@qq.com', 'http://localhost:8080/petHospital/upload/1701626776245.png');
INSERT INTO "WENSON"."YONGHU" VALUES ('14', TO_DATE('2023-12-06 01:48:22', 'SYYYY-MM-DD HH24:MI:SS'), '用户4', '123456', '姓名4', '男', '4', '13823888884', '773890004@qq.com', 'http://localhost:8080/petHospital/upload/1701626786814.png');
INSERT INTO "WENSON"."YONGHU" VALUES ('15', TO_DATE('2023-12-06 01:48:22', 'SYYYY-MM-DD HH24:MI:SS'), '用户5', '123456', '姓名5', '男', '5', '13823888885', '773890005@qq.com', 'http://localhost:8080/petHospital/upload/1701626795891.png');
INSERT INTO "WENSON"."YONGHU" VALUES ('16', TO_DATE('2023-12-06 01:48:22', 'SYYYY-MM-DD HH24:MI:SS'), '用户6', '123456', '姓名6', '男', '6', '13823888886', '773890006@qq.com', 'http://localhost:8080/petHospital/upload/1701626807915.png');
INSERT INTO "WENSON"."YONGHU" VALUES ('1618488891531', TO_DATE('2023-12-06 01:48:22', 'SYYYY-MM-DD HH24:MI:SS'), '01', '01', '01', '女', '33', NULL, NULL, 'http://localhost:8080/petHospital/upload/1701626817220.png');
INSERT INTO "WENSON"."YONGHU" VALUES ('1701764322363', TO_DATE('2023-12-06 01:48:22', 'SYYYY-MM-DD HH24:MI:SS'), '02', '02', '02', '男', '18', NULL, NULL, NULL);

-- ----------------------------
-- Primary Key structure for table CHONGWUXINXI
-- ----------------------------
ALTER TABLE "WENSON"."CHONGWUXINXI" ADD CONSTRAINT "SYS_C007645" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table CHONGWUXINXI
-- ----------------------------
ALTER TABLE "WENSON"."CHONGWUXINXI" ADD CONSTRAINT "SYS_C007599" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "WENSON"."CHONGWUXINXI" ADD CONSTRAINT "SYS_C007600" CHECK ("ADDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "WENSON"."CHONGWUXINXI" ADD CONSTRAINT "SYS_C007601" CHECK ("CHONGWUMINGCHENG" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "WENSON"."CHONGWUXINXI" ADD CONSTRAINT "SYS_C007602" CHECK ("PINZHONG" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table CHONGWUXINXI
-- ----------------------------
CREATE UNIQUE INDEX "WENSON"."CHONGWUBIANHAO"
  ON "WENSON"."CHONGWUXINXI" ("CHONGWUBIANHAO" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- Primary Key structure for table CONFIG
-- ----------------------------
ALTER TABLE "WENSON"."CONFIG" ADD CONSTRAINT "SYS_C007643" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table CONFIG
-- ----------------------------
ALTER TABLE "WENSON"."CONFIG" ADD CONSTRAINT "SYS_C007597" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "WENSON"."CONFIG" ADD CONSTRAINT "SYS_C007598" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table FORUM
-- ----------------------------
ALTER TABLE "WENSON"."FORUM" ADD CONSTRAINT "SYS_C007644" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table FORUM
-- ----------------------------
ALTER TABLE "WENSON"."FORUM" ADD CONSTRAINT "SYS_C007606" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "WENSON"."FORUM" ADD CONSTRAINT "SYS_C007607" CHECK ("ADDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "WENSON"."FORUM" ADD CONSTRAINT "SYS_C007608" CHECK ("CONTENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "WENSON"."FORUM" ADD CONSTRAINT "SYS_C007609" CHECK ("USERID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table GUAHAOYUYUE
-- ----------------------------
ALTER TABLE "WENSON"."GUAHAOYUYUE" ADD CONSTRAINT "SYS_C007646" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table GUAHAOYUYUE
-- ----------------------------
ALTER TABLE "WENSON"."GUAHAOYUYUE" ADD CONSTRAINT "SYS_C007603" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "WENSON"."GUAHAOYUYUE" ADD CONSTRAINT "SYS_C007604" CHECK ("ADDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "WENSON"."GUAHAOYUYUE" ADD CONSTRAINT "SYS_C007605" CHECK ("YONGHUMING" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table JIYANG
-- ----------------------------
ALTER TABLE "WENSON"."JIYANG" ADD CONSTRAINT "SYS_C007648" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table JIYANG
-- ----------------------------
ALTER TABLE "WENSON"."JIYANG" ADD CONSTRAINT "SYS_C007619" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "WENSON"."JIYANG" ADD CONSTRAINT "SYS_C007620" CHECK ("ADDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table JIYANGJIEGUO
-- ----------------------------
ALTER TABLE "WENSON"."JIYANGJIEGUO" ADD CONSTRAINT "SYS_C007650" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table JIYANGJIEGUO
-- ----------------------------
ALTER TABLE "WENSON"."JIYANGJIEGUO" ADD CONSTRAINT "SYS_C007617" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "WENSON"."JIYANGJIEGUO" ADD CONSTRAINT "SYS_C007618" CHECK ("ADDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table LINGYANG
-- ----------------------------
ALTER TABLE "WENSON"."LINGYANG" ADD CONSTRAINT "SYS_C007649" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table LINGYANG
-- ----------------------------
ALTER TABLE "WENSON"."LINGYANG" ADD CONSTRAINT "SYS_C007610" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "WENSON"."LINGYANG" ADD CONSTRAINT "SYS_C007611" CHECK ("ADDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table NEWS
-- ----------------------------
ALTER TABLE "WENSON"."NEWS" ADD CONSTRAINT "SYS_C007647" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table NEWS
-- ----------------------------
ALTER TABLE "WENSON"."NEWS" ADD CONSTRAINT "SYS_C007612" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "WENSON"."NEWS" ADD CONSTRAINT "SYS_C007613" CHECK ("ADDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "WENSON"."NEWS" ADD CONSTRAINT "SYS_C007614" CHECK ("TITLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "WENSON"."NEWS" ADD CONSTRAINT "SYS_C007615" CHECK ("PICTURE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "WENSON"."NEWS" ADD CONSTRAINT "SYS_C007616" CHECK ("CONTENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table STOREUP
-- ----------------------------
ALTER TABLE "WENSON"."STOREUP" ADD CONSTRAINT "SYS_C007652" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table STOREUP
-- ----------------------------
ALTER TABLE "WENSON"."STOREUP" ADD CONSTRAINT "SYS_C007621" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "WENSON"."STOREUP" ADD CONSTRAINT "SYS_C007622" CHECK ("ADDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "WENSON"."STOREUP" ADD CONSTRAINT "SYS_C007624" CHECK ("USERID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "WENSON"."STOREUP" ADD CONSTRAINT "SYS_C007626" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "WENSON"."STOREUP" ADD CONSTRAINT "SYS_C007629" CHECK ("PICTURE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table TOKEN
-- ----------------------------
ALTER TABLE "WENSON"."TOKEN" ADD CONSTRAINT "SYS_C007653" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table TOKEN
-- ----------------------------
ALTER TABLE "WENSON"."TOKEN" ADD CONSTRAINT "SYS_C007623" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "WENSON"."TOKEN" ADD CONSTRAINT "SYS_C007625" CHECK ("USERID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "WENSON"."TOKEN" ADD CONSTRAINT "SYS_C007628" CHECK ("USERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "WENSON"."TOKEN" ADD CONSTRAINT "SYS_C007631" CHECK ("TOKEN" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "WENSON"."TOKEN" ADD CONSTRAINT "SYS_C007632" CHECK ("ADDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "WENSON"."TOKEN" ADD CONSTRAINT "SYS_C007633" CHECK ("EXPIRATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table USERS
-- ----------------------------
ALTER TABLE "WENSON"."USERS" ADD CONSTRAINT "SYS_C007651" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table USERS
-- ----------------------------
ALTER TABLE "WENSON"."USERS" ADD CONSTRAINT "SYS_C007634" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "WENSON"."USERS" ADD CONSTRAINT "SYS_C007635" CHECK ("USERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "WENSON"."USERS" ADD CONSTRAINT "SYS_C007636" CHECK ("PASSWORD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "WENSON"."USERS" ADD CONSTRAINT "SYS_C007637" CHECK ("ADDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table YISHENGXINXI
-- ----------------------------
ALTER TABLE "WENSON"."YISHENGXINXI" ADD CONSTRAINT "SYS_C007654" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table YISHENGXINXI
-- ----------------------------
ALTER TABLE "WENSON"."YISHENGXINXI" ADD CONSTRAINT "SYS_C007627" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "WENSON"."YISHENGXINXI" ADD CONSTRAINT "SYS_C007630" CHECK ("ADDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table YONGHU
-- ----------------------------
ALTER TABLE "WENSON"."YONGHU" ADD CONSTRAINT "SYS_C007655" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table YONGHU
-- ----------------------------
ALTER TABLE "WENSON"."YONGHU" ADD CONSTRAINT "SYS_C007638" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "WENSON"."YONGHU" ADD CONSTRAINT "SYS_C007639" CHECK ("ADDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "WENSON"."YONGHU" ADD CONSTRAINT "SYS_C007640" CHECK ("YONGHUMING" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "WENSON"."YONGHU" ADD CONSTRAINT "SYS_C007641" CHECK ("MIMA" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "WENSON"."YONGHU" ADD CONSTRAINT "SYS_C007642" CHECK ("XINGMING" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table YONGHU
-- ----------------------------
CREATE UNIQUE INDEX "WENSON"."YONGHUMING"
  ON "WENSON"."YONGHU" ("YONGHUMING" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
